name: netcalc
version: 0.1.0
description: A network characteristics calculator for the commandline.
dependencies:
  cli11:
    git:
      url: https://github.com/CLIUtils/CLI11.git
      ref: v2.4.2
environment:
  sdk: ">=2.12.0 <3.0.0"